# Generated by Django 4.0.4 on 2022-05-29 22:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='squareImage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, size=[2878, 1618], upload_to='square/'),
        ),
    ]
