# Generated by Django 4.0.4 on 2022-05-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_delete_location_category_slug_category_uniqueid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['imageName']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uniqueId',
        ),
    ]
