# Generated by Django 4.0.4 on 2022-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_alter_image_squareimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='squareImage',
            field=models.ImageField(blank=True, upload_to='square/'),
        ),
    ]
