# Generated by Django 4.0.4 on 2022-05-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_alter_image_options_remove_image_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='uniqueId',
        ),
    ]
