# Generated by Django 4.0.4 on 2022-05-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0007_image_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
    ]
